sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pauloes/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pauloes/react-test npm test -- --coverage

after_success:
  # Build images
  - docker build -t pauloes/multi-client ./client
  - docker build -t pauloes/multi-nginx ./nginx
  - docker build -t pauloes/multi-server ./server
  - docker build -t pauloes/multi-worker ./worker

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
