sudo: required
services:
  - docker

before_install:
  - docker build -t pauloes/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pauloes/react-test npm test -- --coverage

after_success:
  - docker build -t pauloes/multi-client ./client
  - docker build -t pauloes/multi-nginx ./nginx
  - docker build -t pauloes/multi-server ./server
  - docker build -t pauloes/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push pauloes/multi-client
  - docker push pauloes/multi-nginx
  - docker push pauloes/multi-server
  - docker push pauloes/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-314678225910
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
# deploy:
#   edge: true
#   provider: elasticbeanstalk
