sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pauloes/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pauloes/react-test npm test -- --coverage

after_success:
  # Build images
  - docker build -t pauloes/multi-client ./client
  - docker build -t pauloes/multi-nginx ./nginx
  - docker build -t pauloes/multi-server ./server
  - docker build -t pauloes/multi-worker ./worker
  # Log in to the docker CLI
  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
  # Take those images and push them to docker hub
  - docker push pauloes/multi-client
  - docker push pauloes/multi-nginx
  - docker push pauloes/multi-server
  - docker push pauloes/multi-worker
