#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
Take those images and push them to docker hub
docker push pauloes/multi-client
docker push pauloes/multi-nginx
docker push pauloes/multi-server
docker push pauloes/multi-worker
